name: Build TL Documentation

on:
  push:
    paths:
      - 'src/Tl/api.tl'
  pull_request:
    paths:
      - 'src/Tl/api.tl'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PHP_VERSION: '8.3'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@2.32.0
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, gmp
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --working-dir=docs

      - name: Run render
        run: php docs/render.php

      - name: Remove vendor
        run: |
          rm -rf docs/vendor
          rm -f docs/composer.lock

      - name: GitHub Commit & Push
        uses: actions-js/push@v1.5
        with:
          message: "Update Layer & TL Documentation"
          github_token: ${{ secrets.GITHUB_TOKEN }}
